version: 1.0.{build}

image:
  - Visual Studio 2019

platform:
  - x64

init:
  - git config --global core.autocrlf input
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - node -p "process.cwd()"
  - git clone https://github.com/cjihrig/uvwasi
  - git clone https://github.com/libuv/libuv
  - choco install clion-ide
  - choco install nodejs
  - choco install mingw

build_script:
  - npx envinfo
  
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

test: off
