version: 1.0.{build}

image:
  - Visual Studio 2019 Preview 

platform:
  - x64

init:
  - git config --global core.autocrlf input
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - node -p "process.cwd()"
  - choco install nasm vscode nodejs 
  - npx envinfo
  - git clone -b vs2019-build --single-branch https://github.com/gengjiawen/node-v8 --depth=10
  - git clone https://github.com/nodejs/node --depth=1
  - git clone https://github.com/cjihrig/uvwasi
  - git clone https://github.com/libuv/libuv
  - cd node-v8 && .\vcbuild.bat
  - choco install clion-ide

  
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

test: off
