image: macOS

install:
  - node -p "process.cwd()"
  - npx envinfo

on_finish:
  - sh: export APPVEYOR_VNC_BLOCK=true
  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-vnc.sh' | bash -e -
test: off
