version: 1.0.{build}

image:
  - Visual Studio 2017

platform:
  - x64

init:
  - git config --global core.autocrlf input
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - node -p "process.cwd()"
  - choco install nasm vscode hub
  - git clone https://github.com/nodejs/node-gyp
  - cd node-gyp
  - hub pr checkout 1975
  - yarn
  - yarn test

build_script:
  - npx envinfo
  
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

test: off
