version: 1.0.{build}

image:
  - Visual Studio 2017

platform:
  - x64

init:
  - git config --global core.autocrlf input
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - npx envinfo
  - node -p "process.cwd()"
  - choco install nasm vscode 
  - git clone https://github.com/gengjiawen/node-v8 --depth=10 
  - git clone -b canary-base --single-branch https://github.com/nodejs/node --depth=10
  - git clone https://github.com/cjihrig/uvwasi
  - git clone https://github.com/libuv/libuv
  - cd node-v8 && .\vcbuild.bat
  - refreshenv && code .
  - choco install clion-ide nodejs
  
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

test: off
