version: 1.0.{build}

image:
  - Visual Studio 2022 Preview

platform:
  - x64

init:
  - git config --global core.autocrlf input
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - node -p "process.cwd()"
  - choco install nasm vscode nodejs
  - npx envinfo
  - cd C:\users\appveyor\Desktop
#   - git clone https://github.com/nodejs/node-v8 --depth=10
  - git clone -b c++20 --single-branch https://github.com/targos/node --depth=10	
  - cd node && .\vcbuild.bat noetw
#   - choco install clion-ide

  
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

test: off
